name: MCC
version: '${project.version}'
main: com.mimikcraft.mcc.Main
api-version: '1.16'
commands:
  join:
    usage: /join
  leave:
    usage: /leave
  faststart:
    usage: /faststart
  gamesettings:
    usage: /gamesettings
  party:
    usage: /party
  setspawns:
    usage: /setspawns
  getchest:
    usage: /getchest
  bestiary:
    usage: /bestiary
  prestige:
    usage: /prestige
  launch:
    usage: /launch
    aliases:
      - startgame
      - launchgame
      - start
depend:
  - MythicMobs
  - Vault
softdepend:
  - ExecutableItems
  - SCore


