name: MCC
version: '${project.version}'
main: com.mimikcraft.mcc.Main
api-version: '1.16'
commands:
  join:
    usage: /join
  leave:
    usage: /leave
depend:
  - MythicMobs
  - Vault
softdepend:
  - ExecutableItems
  - SCore

