Artifacts:
  von: #7
    - 4
    - 2
    - 1
  speed: #14
    - 8
    - 4
    - 2
  strength: #10
    - 5
    - 3
    - 2
  jumpboost: #14
    - 8
    - 4
    - 2
  kachumber: #7
    - 4
    - 2
    - 1
  bread: #7
    - 4
    - 2
    - 1
  oil: #10
    - 5
    - 3
    - 2
  doblejump: #5
    - 5
  regeneration: #10
    - 5
    - 3
    - 2
  pill: #7
    - 4
    - 2
    - 1
  bones: #5
    - 5
  totem: #7
    - 4
    - 2
    - 1
  contract: #7
    - 4
    - 2
    - 1
