name: MCC
version: '1.0.0'
main: com.mimikcraft.mcc.Main
api-version: '1.16'
commands:
  join:
    usage: /join
  leave:
    usage: /leave
  forcestart:
    usage: /forcestart
  gamesettings:
    usage: /gamesettings
  party:
    usage: /party
  setspawns:
    usage: /setspawns
  getchest:
    usage: /getchest
  bestiary:
    usage: /bestiary
  prestige:
    usage: /prestige
  arenakick:
    usage: /arenakick
  launch:
    usage: /launch
    aliases:
      - startgame
      - launchgame
      - start
  choosestructurechanges:
    usage: /chooseStructureChange
  setstructurechanges:
    usage: /setStructureChanges
  revive:
    usage: /revive
  addlife:
    usage: /addlife
depend:
  - MythicMobs
  - Vault
  - TAB
softdepend:
  - ExecutableItems
  - SCore
  - PlaceholderAPI


