name: MCC
version: '1.0.0'
main: com.mimikcraft.mcc.Main
api-version: '1.16'
commands:
  join:
    usage: /join
  leave:
    usage: /leave
  forcestart:
    usage: /forcestart
    aliases:
      - faststart
      - start
  newgame:
    usage: /newgame
    aliases:
      - creategame
      - create
      - launch
      - launchgame
  gamesettings:
    usage: /gamesettings
  party:
    usage: /party
  choosespawns:
    usage: /choosespawns
  setspawns:
    usage: /setspawns
  setchests:
    usage: /setchests
  bestiary:
    usage: /bestiary
  prestige:
    usage: /prestige
  setlocation:
    usage: /setlocation
  test:
    usage: /test
depend:
  - MythicMobs
  - Vault
softdepend:
  - ExecutableItems
  - SCore

