name: MCC
version: '1.0.0'
main: com.mimikcraft.mcc.Main
api-version: '1.16'
commands:
  join:
    usage: /join
  leave:
    usage: /leave
  faststart:
    usage: /faststart
  newgame:
    usage: /newgame
  gamesettings:
    usage: /gamesettings
  party:
    usage: /party
  choosespawns:
    usage: /choosespawns
  setspawns:
    usage: /setspawns
  setchests:
    usage: /setchests
  bestiary:
    usage: /bestiary
  prestige:
    usage: /prestige
  setlocation:
    usage: /setlocation
depend:
  - MythicMobs
  - Vault
softdepend:
  - ExecutableItems
  - SCore

